### ISSUE TITLE
where to store blog post ideas/requests

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkrablog#10]
as clickup tasks?

@christophsax @krlmlr

**Comment by maelle** [comment]
@krlmlr git/GitHub tips like https://fosstodon.org/@kirill/111243275707794127 would make nice short posts. :innocent:

**Comment by maelle** [comment]
I guess these would live as clickup tasks, but it'd be nice to document the process somewhere. In clickup too?

**Comment by christophsax** [comment]
CU makes sense to me. In or next to 'Website' in the General Manual? https://app.clickup.com/4730439/v/dc/4gbj7-2017/4gbj7-10842
