### ISSUE TITLE
different font for headers

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkrablog#13]

**Comment by christophsax** [comment]
The current headers use fake bold:

<img width="863" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/72e8961a-3afa-41e1-8618-64ca54e895c0">

Turning off font-weight: 600 makes it already look better:

<img width="773" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/4ece1695-f15f-42ab-a588-5964d613607d">

However, in cynkraweb, we use the actual `frutiger-thin` for headers (which is *thinner* than the main font).

**Comment by christophsax** [comment]
No, that looks good. Thin and 300. However, there seems to some other issues now:

<img width="885" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/ddf71193-763b-4898-9506-54caf328fe94">
