### ISSUE TITLE
fixed width font

### ISSUE THREAD

**Issue by christophsax** [cynkra/cynkrablog#20]
On Mac safari, the fixed width font is a bit ugly:

<img width="846" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/2afc4b32-b65d-4ae6-b4c1-58c6d1ef915e">

Menlo or Dejavue Sans Mono? Not sure what we are currently using on the website.

**Comment by maelle** [comment]
current website font for code as seen in https://cynkra.com/blog/2022-05-14-accessing-google-api-via-oauth2/

SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace

**Comment by maelle** [comment]
I don't see where the code font is loaded for the website :raised_eyebrow:

**Comment by pat-s** [comment]
For inspiration: In https://server-manual.cynkra.com/dynamic-cifs-mount.html we use `JetBrains Mono` via

```yml
format:
  html:
    monofont: "JetBrains Mono"
```
