### ISSUE TITLE
how to get PR deploy previews

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkrablog#22]
Should we install Netlify on this repo?

I know we use some sort of gh-pages deploy for pkgdown website previews, but it's not a great workflow in the case several posts are in PR state at the same time.

@pat-s

**Comment by pat-s** [comment]
Why is it not great for multiple PRS?

We don't use Netlify anymore. They charge a lot for private repos.

**Comment by maelle** [comment]
Well this is a public repo :grin: but ok, let's find another way.

In the pkgdown previews, all PRs get deployed to dev/, so if you have several PRs, they overwrite each other.

**Comment by pat-s** [comment]
> Well this is a public repo 😁 but ok, let's find another way.

Yeah but even then - we're good without Netlify.

For cynkraweb we use s3-based previews. All of them have their own environment (=bucket) and don't conflict.

So far I thought we use the same preview approach as we do in cynkraweb? I.e. you copy the workflow from there and I add the required secrets. And then things "should just work" :)
