### ISSUE TITLE
Syntax highlighting for YAML & friends

### ISSUE THREAD

**Issue by pat-s** [cynkra/cynkrablog#30]
I noticed that (at least) YAML code blocks are not syntax highlighted, e.g. https://cynkra.github.io/cynkrablog/blog/posts/2020-12-23-dynamic-gha/. 

FYI @maelle

**Comment by maelle** [comment]
Good catch. Probably a stylesheet problem as the classes are added by Pandoc. On it now (it works on my machine :zany_face:)

**Comment by maelle** [comment]
it works on https://blog.cynkra.com/blog/posts/2022-05-14-accessing-google-api-via-oauth2/ and https://blog.cynkra.com/blog/posts/2020-12-23-dynamic-gha/

**Comment by pat-s** [comment]
@maelle Doesn't work for me

![image](https://github.com/cynkra/cynkrablog/assets/8430564/9d334803-06c6-4a4c-a756-e8bcdd9c2529)

Additionally: note the `{% raw %}` placeholder leftover.

**Comment by maelle** [comment]
or only broken for a previous build, maybe it was an old preview. I'll revisit if needed.
