### ISSUE TITLE
EFS post missing

### ISSUE THREAD

**Issue by pat-s** [cynkra/cynkrablog#31]
https://cynkra.com/blog/2022-09-14-rstudio-efs-nfs/

@maelle

**Comment by maelle** [comment]
oh, sorry! on it now.

I see https://github.com/cynkra/cynkraweb/tree/main/www/blog/2022-09-14-rstudio-efs-nfs has no Markdown file.

**Comment by maelle** [comment]
@pat-s was it the latest "must-do" before the redirection?
