### ISSUE TITLE
what placeholder image to use?

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkrablog#4]
https://github.com/cynkra/cynkrablog/blob/f567ae4a0adf7693affb12c1ea6447fb7af6b8e6/index.qmd#L14

**Comment by maelle** [comment]
@christophsax should we keep the cow? :smile_cat: A picture of Zurich would be nice (either a free one, or one that'd have been taken by a team member willing to "donate" it for the website)

**Comment by maelle** [comment]
related https://github.com/quarto-dev/quarto-cli/discussions/6987

**Comment by christophsax** [comment]
How about this: https://unsplash.com/photos/Zi9yS95gDUQ?

We used this on the website in the past.
