### ISSUE TITLE
improve preview workflow

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkrablog#40]
- no longer use GitHub Pages?
- https://github.com/quarto-dev/quarto-actions/issues/96

cc @pat-s

**Comment by pat-s** [comment]
> no longer use GitHub Pages?

No strong opinion. Both are fine (if you refer to S3 as the alternative).

> https://github.com/quarto-dev/quarto-actions/issues/96

Certainly an improvement, even though previews shouldn't stick around for so long that they get indexed and move up in the rankings. *Shouldn't*. But an option in the action would certainly be cool.

**Comment by maelle** [comment]
> Certainly an improvement, even though previews shouldn't stick around for so long that they get indexed and move up in the rankings.

The thing is, if we keep using GitHub Pages, there'll always be a preview around, since the github.io website will be there all the time.
