### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by christophsax** [cynkra/cynkrablog#49]
![image](https://github.com/cynkra/cynkrablog/assets/1390827/3f158f6f-c729-4423-a529-55a3863371e8)

**Comment by maelle** [comment]
Ouch! This is what I see on Firefox:

![image](https://github.com/cynkra/cynkrablog/assets/8360597/17d4f8b0-c80a-472f-b627-796fca951e64)

**Comment by maelle** [comment]
But on Chrome I can see the issue too.

**Comment by maelle** [comment]
Must be a CORS thing, exploring now.

**Comment by maelle** [comment]
Related #15

**Comment by maelle** [comment]
Could it be a CORS isse this time? Or did the rules change in cynkraweb

Font rules 

https://github.com/cynkra/cynkrablog/blob/db8cd197afb7a10c47875b2def397b74a28efc7b/custom.scss#L41-L56

**Comment by christophsax** [comment]
Today is the first time I see this. On all browsers. I am not aware we changed stuff in cynkraweb but then I may overlook something.

**Comment by maelle** [comment]
I don't see changes in the relevant cynkraweb scss file.
I don't see any error in the web developer console.

**Comment by DivadNojnarg** [comment]
I managed to see a CORS error:

```js
blog.cynkra.com/:1 
Access to font at 'https://cynkra.com/assets/css/fonts/1449009/b3ca2df2-7bee-4fc0-84cb-b029b99c3b61.woff2' from origin 'https://blog.cynkra.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.cynkra.com' that is not equal to the supplied origin.
```

**Comment by maelle** [comment]
@pat-s is this an easy CORS switch? sorry to bother you once again about fonts :sweat_smile:

**Comment by pat-s** [comment]
CORS is fixed, but it seems the font still cannot be loaded from the source.

**Comment by maelle** [comment]
Thank you! Do you have any idea what might be wrong? I'll explore more next Monday...

**Comment by maelle** [comment]
I have the issue for the preview at GitHub pages, but https://blog.cynkra.com/ looks ok to me now?!

**Comment by maelle** [comment]
I wonder whether this could be linked to the font files that had the "wrong" names at one point @christophsax @pat-s?

**Comment by pat-s** [comment]
https://blog.cynkra.com/ is still not showing fonts. You can check this in a private window.

There are no devtools errors in the browser about something being blocked or not accessible, so the issue is likely in the source/css somewhere.

**Comment by maelle** [comment]
@DivadNojnarg found the typo I had made :woman_facepalming:
