### ISSUE TITLE
How to preview?

### ISSUE THREAD

**Issue by christophsax** [cynkra/cynkrablog#54]
I guess some kind of preview is built during a PR, but how can I access it?

**Comment by DivadNojnarg** [comment]
@maelle: can it be cynkra.github.io/cynkrablog?

**Comment by maelle** [comment]
@DivadNojnarg yes it is https://github.com/cynkra/cynkrablog/blob/4bcd389a675e5ff2d9314692054aeaadf1c453a1/.github/workflows/publish.yml#L64

so it means two PRs will compete to deploy to the same link.

**Comment by christophsax** [comment]
Thanks, good enough for me. I updated the README.
